# Generated by Django 4.2.1 on 2023-05-10 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test2", "0003_order_customer_order_product"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name="order",
            name="tags",
            field=models.ManyToManyField(to="test2.tag"),
        ),
    ]
