# Generated by Django 4.2.1 on 2023-05-10 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test2", "0004_tag_order_tags"),
    ]

    operations = [
        migrations.RemoveField(model_name="order", name="tags",),
        migrations.AddField(
            model_name="product",
            name="tags",
            field=models.ManyToManyField(to="test2.tag"),
        ),
    ]
