# Generated by Django 4.2.1 on 2023-05-11 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test2", "0005_remove_order_tags_product_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="note",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Out of delivery", "Out of delivery"),
                    ("Delivered", "Delivered"),
                ],
                max_length=1000,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
