# Generated by Django 4.2.1 on 2023-05-11 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test2", "0006_order_note_alter_product_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="note",
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
