# Generated by Django 4.2.1 on 2023-05-15 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test2", "0008_customer_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="profile_pic",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
